name: Deploy to DEV environment
on:
  workflow_call:

jobs:
  deploy-dev:
    runs-on: [self-hosted, Linux]
    # environment: DEV
    # if: ${{ github.event_name != 'pull_request' && github.ref_name == 'dev' }}
    env:
      KUBE_HOST: ${{ secrets.KUBE_HOST }}
      KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
    steps:
      - name: Deploy new image version
        uses: actions-hub/kubectl@v1.26.3
        with:
          args: --namespace defguard-dev set image deployment/defguard defguard=ghcr.io/defguard/defguard:sha-${{ github.sha }}
