name: Create SBOM files

on:
  workflow_call:
    inputs:
      upload_url:
        description: "Release assets upload URL"
        required: true
        type: string
      tag:
        description: "The git tag to generate SBOM for - used in scheduled runs"
        required: false
        type: string

jobs:
  create-sbom:
    permissions:
      contents: write
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Determine release tag and version
        id: vars
        # Uses inputs.tag for scheduled runs, otherwise github.ref_name.
        run: |
          TAG_NAME=${{ inputs.tag || github.ref_name }}
          VERSION=${TAG_NAME#v}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.TAG_NAME }}
          submodules: recursive

      - name: Create SBOM with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          format: 'spdx-json'
          output: "defguard-${{ steps.vars.outputs.VERSION }}.sbom.json"
          scan-ref: '.'
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          scanners: "vuln"
          skip-dirs: "e2e"

      - name: Create docker image SBOM with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "ghcr.io/defguard/defguard:${{ steps.vars.outputs.VERSION }}"
          scan-type: 'image'
          format: 'spdx-json'
          output: "defguard-${{ steps.vars.outputs.VERSION }}-docker.sbom.json"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          scanners: "vuln"

      - name: Create security advisory file with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          format: 'json'
          output: "defguard-${{ steps.vars.outputs.VERSION }}.advisories.json"
          scan-ref: '.'
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          scanners: "vuln"
          skip-dirs: "e2e"

      - name: Create docker image security advisory file with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "ghcr.io/defguard/gateway:${{ steps.vars.outputs.VERSION }}"
          scan-type: 'image'
          format: 'json'
          output: "defguard-${{ steps.vars.outputs.VERSION }}-docker.advisories.json"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          scanners: "vuln"

      - name: Upload SBOMs and advisories
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: "defguard-*.json"
          asset_content_type: application/octet-stream
          overwrite: true
