name: Deploy to webnext environment
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    branches:
      - webnext
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build-image:
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=ref,event=branch
        type=sha

  deploy-webnext:
    needs: build-image
    runs-on: [self-hosted, Linux, X64]
    environment: WEBNEXT
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'webnext' }}
    env:
      KUBE_HOST: ${{ secrets.KUBE_HOST }}
      KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
    steps:
      - name: Add SHORT_SHA env variable
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - name: Deploy new image version
        uses: actions-hub/kubectl@v1.30.3
        with:
          args: --namespace defguard-filip set image deployment/defguard defguard=ghcr.io/defguard/defguard:sha-${{ env.SHORT_SHA }}
